{
 "title": "Dashboard Pasarela de Pagos (Flux)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pagos Confirmados",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"TallerJava\") |> range(start: -30m) |> filter(fn: (r) => r._measurement == \"payment_ok\" and r._field == \"value\")"
    }
   ]
  },
  {
   "title": "Pagos Rechazados",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"TallerJava\") |> range(start: -30m) |> filter(fn: (r) => r._measurement == \"payment_fail\" and r._field == \"value\")"
    }
   ]
  },
  {
   "title": "Reportes de Ventas",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"TallerJava\") |> range(start: -30m) |> filter(fn: (r) => r._measurement == \"sales_report\" and r._field == \"value\")"
    }
   ]
  },
  {
   "title": "Depósitos en Banco",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"TallerJava\") |> range(start: -30m) |> filter(fn: (r) => r._measurement == \"deposit\" and r._field == \"value\")"
    }
   ]
  },
  {
   "title": "Reclamos",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"TallerJava\") |> range(start: -30m) |> filter(fn: (r) => r._measurement == \"complaint\" and r._field == \"value\")"
    }
   ]
  }
 ]
}